// Données fictives

import {
  Camion,
  Chauffeur,
  Client,
  Livraison,
  Produit,
  SiteLivraison,
  Utilisateur,
} from "./types";

export const utilisateurs: Utilisateur[] = [
  { id: 1, nom: "Admin", role: "admin", email: "admin@example.com" },
  { id: 2, nom: "Dupont", role: "chauffeur", email: "dupont@example.com" },
  { id: 3, nom: "Curie", role: "client", email: "curie@example.com" },
  { id: 4, nom: "Martin", role: "client", email: "martin@example.com" },
  { id: 5, nom: "Durand", role: "chauffeur", email: "durand@example.com" },
  { id: 6, nom: "Petit", role: "client", email: "petit@example.com" },
  { id: 7, nom: "Roux", role: "client", email: "roux@example.com" },
  { id: 8, nom: "Leroy", role: "chauffeur", email: "leroy@example.com" },
  { id: 9, nom: "Simon", role: "client", email: "simon@example.com" },
  { id: 10, nom: "Moreau", role: "chauffeur", email: "moreau@example.com" },
  { id: 11, nom: "Bernard", role: "client", email: "bernard@example.com" },
  { id: 12, nom: "Dubois", role: "chauffeur", email: "dubois@example.com" },
  { id: 13, nom: "Thomas", role: "client", email: "thomas@example.com" },
  { id: 14, nom: "Robert", role: "client", email: "robert@example.com" },
  { id: 15, nom: "Richard", role: "autre", email: "richard@example.com" },
];

export const produits: Produit[] = [
  { id: 1, nom: "Essence", description: "Carburant pour moteurs à essence" },
  { id: 2, nom: "Gasoil", description: "Carburant pour moteurs diesel" },
  { id: 3, nom: "Kérosène", description: "Carburant pour avions" },
  { id: 4, nom: "GPL", description: "Gaz de pétrole liquéfié" },
  { id: 5, nom: "Bitume", description: "Produit pour revêtement routier" },
  { id: 6, nom: "Mazout", description: "Carburant pour chauffage" },
  {
    id: 7,
    nom: "Huiles lubrifiantes",
    description: "Entretien et maintenance",
  },
  { id: 8, nom: "Bioéthanol", description: "Carburant renouvelable" },
  { id: 9, nom: "Biodiesel", description: "Diesel renouvelable" },
  { id: 10, nom: "Supercarburant", description: "Formule performante" },
  { id: 11, nom: "Carburant marin", description: "Pour bateaux et navires" },
  { id: 12, nom: "Carburant agricole", description: "Pour machines agricoles" },
  { id: 13, nom: "Carburant de secours", description: "Utilisé en urgence" },
  { id: 14, nom: "Carburant premium", description: "Haute performance" },
  { id: 15, nom: "Carburant standard", description: "Norme de l'industrie" },
];

export const clients: Client[] = [
  { id: 1, nom: "Total", contact: "contact@total.com", adresse: "Paris" },
  { id: 2, nom: "Shell", contact: "contact@shell.com", adresse: "Londres" },
  { id: 3, nom: "BP", contact: "contact@bp.com", adresse: "New York" },
  {
    id: 4,
    nom: "ExxonMobil",
    contact: "contact@exxonmobil.com",
    adresse: "Houston",
  },
  {
    id: 5,
    nom: "Chevron",
    contact: "contact@chevron.com",
    adresse: "Los Angeles",
  },
  {
    id: 6,
    nom: "TotalEnergies",
    contact: "contact@totalenergies.com",
    adresse: "Marseille",
  },
  { id: 7, nom: "Eni", contact: "contact@eni.com", adresse: "Milan" },
  { id: 8, nom: "Repsol", contact: "contact@repsol.com", adresse: "Madrid" },
  {
    id: 9,
    nom: "ConocoPhillips",
    contact: "contact@conocophillips.com",
    adresse: "Calgary",
  },
  { id: 10, nom: "Lukoil", contact: "contact@lukoil.com", adresse: "Moscou" },
  {
    id: 11,
    nom: "Petrobras",
    contact: "contact@petrobras.com",
    adresse: "Rio de Janeiro",
  },
  { id: 12, nom: "Statoil", contact: "contact@statoil.com", adresse: "Oslo" },
  {
    id: 13,
    nom: "Rosneft",
    contact: "contact@rosneft.com",
    adresse: "Saint-Pétersbourg",
  },
  { id: 14, nom: "Gazprom", contact: "contact@gazprom.com", adresse: "Moscou" },
  { id: 15, nom: "Eni", contact: "contact@eni2.com", adresse: "Rome" },
];

export const sitesLivraison: SiteLivraison[] = [
  { id: 1, nom: "Site A", distance: 10, prixLivraison: 100 },
  { id: 2, nom: "Site B", distance: 20, prixLivraison: 180 },
  { id: 3, nom: "Site C", distance: 5, prixLivraison: 60 },
  { id: 4, nom: "Site D", distance: 15, prixLivraison: 140 },
  { id: 5, nom: "Site E", distance: 25, prixLivraison: 220 },
  { id: 6, nom: "Site F", distance: 30, prixLivraison: 270 },
  { id: 7, nom: "Site G", distance: 8, prixLivraison: 90 },
  { id: 8, nom: "Site H", distance: 12, prixLivraison: 120 },
  { id: 9, nom: "Site I", distance: 18, prixLivraison: 160 },
  { id: 10, nom: "Site J", distance: 22, prixLivraison: 200 },
  { id: 11, nom: "Site K", distance: 7, prixLivraison: 80 },
  { id: 12, nom: "Site L", distance: 16, prixLivraison: 150 },
  { id: 13, nom: "Site M", distance: 28, prixLivraison: 250 },
  { id: 14, nom: "Site N", distance: 35, prixLivraison: 320 },
  { id: 15, nom: "Site O", distance: 3, prixLivraison: 40 },
];

export const chauffeurs: Chauffeur[] = [
  {
    id: 1,
    nom: "Dupont",
    prenom: "Jean",
    contact: "jean.dupont@example.com",
    documents: ["permis", "identité"],
  },
  {
    id: 2,
    nom: "Durand",
    prenom: "Sophie",
    contact: "sophie.durand@example.com",
    documents: ["permis", "assurance"],
  },
  {
    id: 3,
    nom: "Martin",
    prenom: "Lucas",
    contact: "lucas.martin@example.com",
    documents: ["permis"],
  },
  {
    id: 4,
    nom: "Lefevre",
    prenom: "Emma",
    contact: "emma.lefevre@example.com",
    documents: ["permis", "contrat"],
  },
  {
    id: 5,
    nom: "Moreau",
    prenom: "Hugo",
    contact: "hugo.moreau@example.com",
    documents: ["permis"],
  },
  {
    id: 6,
    nom: "Girard",
    prenom: "Alice",
    contact: "alice.girard@example.com",
    documents: ["permis", "identité"],
  },
  {
    id: 7,
    nom: "Roux",
    prenom: "Victor",
    contact: "victor.roux@example.com",
    documents: ["permis", "assurance"],
  },
  {
    id: 8,
    nom: "Petit",
    prenom: "Chloé",
    contact: "chloe.petit@example.com",
    documents: ["permis"],
  },
  {
    id: 9,
    nom: "Garnier",
    prenom: "Noah",
    contact: "noah.garnier@example.com",
    documents: ["permis", "contrat"],
  },
  {
    id: 10,
    nom: "Fournier",
    prenom: "Léa",
    contact: "lea.fournier@example.com",
    documents: ["permis"],
  },
  {
    id: 11,
    nom: "Martinez",
    prenom: "Gabriel",
    contact: "gabriel.martinez@example.com",
    documents: ["permis", "identité"],
  },
  {
    id: 12,
    nom: "Blanc",
    prenom: "Julien",
    contact: "julien.blanc@example.com",
    documents: ["permis", "assurance"],
  },
  {
    id: 13,
    nom: "Legrand",
    prenom: "Clara",
    contact: "clara.legrand@example.com",
    documents: ["permis"],
  },
  {
    id: 14,
    nom: "Boucher",
    prenom: "Antoine",
    contact: "antoine.boucher@example.com",
    documents: ["permis", "contrat"],
  },
  {
    id: 15,
    nom: "Noir",
    prenom: "Camille",
    contact: "camille.noir@example.com",
    documents: ["permis"],
  },
];

export const camions: Camion[] = [
  {
    id: 1,
    tracteur: { id: 1, chauffeurId: 2 },
    remorque: { id: 1, immatriculation: "REM-001" },
  },
  {
    id: 2,
    tracteur: { id: 2, chauffeurId: 5 },
    remorque: { id: 2, immatriculation: "REM-002" },
  },
  {
    id: 3,
    tracteur: { id: 3, chauffeurId: 8 },
    remorque: { id: 3, immatriculation: "REM-003" },
  },
  {
    id: 4,
    tracteur: { id: 4, chauffeurId: 10 },
    remorque: { id: 4, immatriculation: "REM-004" },
  },
  {
    id: 5,
    tracteur: { id: 5, chauffeurId: 12 },
    remorque: { id: 5, immatriculation: "REM-005" },
  },
  {
    id: 6,
    tracteur: { id: 6, chauffeurId: 1 },
    remorque: { id: 6, immatriculation: "REM-006" },
  },
  {
    id: 7,
    tracteur: { id: 7, chauffeurId: 3 },
    remorque: { id: 7, immatriculation: "REM-007" },
  },
  {
    id: 8,
    tracteur: { id: 8, chauffeurId: 4 },
    remorque: { id: 8, immatriculation: "REM-008" },
  },
  {
    id: 9,
    tracteur: { id: 9, chauffeurId: 7 },
    remorque: { id: 9, immatriculation: "REM-009" },
  },
  {
    id: 10,
    tracteur: { id: 10, chauffeurId: 9 },
    remorque: { id: 10, immatriculation: "REM-010" },
  },
  {
    id: 11,
    tracteur: { id: 11, chauffeurId: 6 },
    remorque: { id: 11, immatriculation: "REM-011" },
  },
  {
    id: 12,
    tracteur: { id: 12, chauffeurId: 11 },
    remorque: { id: 12, immatriculation: "REM-012" },
  },
  {
    id: 13,
    tracteur: { id: 13, chauffeurId: 13 },
    remorque: { id: 13, immatriculation: "REM-013" },
  },
  {
    id: 14,
    tracteur: { id: 14, chauffeurId: 14 },
    remorque: { id: 14, immatriculation: "REM-014" },
  },
  {
    id: 15,
    tracteur: { id: 15, chauffeurId: 15 },
    remorque: { id: 15, immatriculation: "REM-015" },
  },
];

export const livraisons: Livraison[] = [
  { id: 1, remorqueId: 1, clientId: 1, siteLivraisonId: 1, produitId: 1 },
  { id: 2, remorqueId: 2, clientId: 2, siteLivraisonId: 2, produitId: 2 },
  { id: 3, remorqueId: 3, clientId: 3, siteLivraisonId: 3, produitId: 3 },
  { id: 4, remorqueId: 4, clientId: 4, siteLivraisonId: 4, produitId: 4 },
  { id: 5, remorqueId: 5, clientId: 5, siteLivraisonId: 5, produitId: 5 },
  { id: 6, remorqueId: 6, clientId: 6, siteLivraisonId: 6, produitId: 6 },
  { id: 7, remorqueId: 7, clientId: 7, siteLivraisonId: 7, produitId: 7 },
  { id: 8, remorqueId: 8, clientId: 8, siteLivraisonId: 8, produitId: 8 },
  { id: 9, remorqueId: 9, clientId: 9, siteLivraisonId: 9, produitId: 9 },
  { id: 10, remorqueId: 10, clientId: 10, siteLivraisonId: 10, produitId: 10 },
  { id: 11, remorqueId: 11, clientId: 11, siteLivraisonId: 11, produitId: 11 },
  { id: 12, remorqueId: 12, clientId: 12, siteLivraisonId: 12, produitId: 12 },
  { id: 13, remorqueId: 13, clientId: 13, siteLivraisonId: 13, produitId: 13 },
  { id: 14, remorqueId: 14, clientId: 14, siteLivraisonId: 14, produitId: 14 },
  { id: 15, remorqueId: 15, clientId: 15, siteLivraisonId: 15, produitId: 15 },
];
